<?php
require_once __DIR__.'/../includes/bootstrap.php'; require_role('commercial_manager');
$user=current_user(); $flashes=render_flashes(); $currentPage='dashboard'; $pageTitle='Commercial Manager Dashboard';
require_once __DIR__.'/_helpers.php'; $conn=Database::getConnection(); $managerId=(int)($user['id']??$user['user_id']??0);
if($managerId<=0){http_response_code(403);exit('Invalid Commercial Manager account.');}
$stats=['searches'=>0,'packs'=>0,'generated'=>0,'suppressed'=>0];
if(cm_table($conn,'commercial_saved_searches')){$s=$conn->prepare("SELECT COUNT(*) total FROM commercial_saved_searches WHERE commercial_manager_id=?");$s->bind_param('i',$managerId);$s->execute();$stats['searches']=(int)($s->get_result()->fetch_assoc()['total']??0);$s->close();}
if(cm_table($conn,'commercial_capability_packs')){$s=$conn->prepare("SELECT COUNT(*) packs,SUM(status='generated') generated,SUM(suppressed_group_count>0) suppressed FROM commercial_capability_packs WHERE commercial_manager_id=?");$s->bind_param('i',$managerId);$s->execute();$r=$s->get_result()->fetch_assoc()?:[];$stats=array_merge($stats,$r);$s->close();}
$packs=[]; if(cm_table($conn,'commercial_capability_packs')){$s=$conn->prepare("SELECT cp.id,cp.pack_name,cp.tender_reference,cp.status,cp.total_candidate_count,cp.suppressed_group_count,ss.search_name FROM commercial_capability_packs cp JOIN commercial_saved_searches ss ON ss.id=cp.saved_search_id WHERE cp.commercial_manager_id=? ORDER BY cp.created_at DESC LIMIT 5");$s->bind_param('i',$managerId);$s->execute();$r=$s->get_result();while($x=$r->fetch_assoc())$packs[]=$x;$s->close();}
$threshold=cm_threshold($conn);$first=trim((string)($user['first_name']??'Commercial Manager'));
require __DIR__.'/_layout_start.php';
?>
<section class="cm-hero"><div><span class="cm-eyebrow"><i class="fas fa-file-shield"></i> Tender Capability Intelligence</span><h2>Evidence capacity without oversharing, <?= e($first) ?>.</h2><p>Generate anonymised capability packs from saved searches, reconcile counts, suppress small groups and direct identifiers, and disclose data currency, criteria and verification breakdowns.</p><div class="cm-hero__actions"><a class="cm-btn cm-btn--light" href="<?= url('commercial_manager/saved_searches.php') ?>"><i class="fas fa-bookmark"></i> Saved Searches</a><a class="cm-btn cm-btn--glass" href="<?= url('commercial_manager/capability_packs.php') ?>"><i class="fas fa-file-shield"></i> Capability Packs</a></div></div><div class="cm-orb"><i class="fas fa-eye-slash"></i><strong>&lt;<?= $threshold ?></strong><span>suppression threshold</span></div></section>
<section class="cm-stats"><article><i class="fas fa-bookmark"></i><strong><?= number_format((int)$stats['searches']) ?></strong><span>Saved Searches</span></article><article><i class="fas fa-file-shield"></i><strong><?= number_format((int)$stats['packs']) ?></strong><span>Capability Packs</span></article><article><i class="fas fa-circle-check"></i><strong><?= number_format((int)$stats['generated']) ?></strong><span>Generated</span></article><article><i class="fas fa-eye-slash"></i><strong><?= number_format((int)$stats['suppressed']) ?></strong><span>Packs With Suppression</span></article></section>
<div class="cm-grid"><section class="cm-card"><div class="cm-card__header"><div><h3>Recent Capability Packs</h3><p>Latest tender evidence packs.</p></div></div><?php if(!$packs): ?><div class="cm-empty"><i class="fas fa-file-shield"></i><strong>No packs yet</strong><span>Generate your first pack from a saved search.</span></div><?php else: ?><div class="cm-list"><?php foreach($packs as $p): ?><a href="<?= url('commercial_manager/pack_view.php?id='.(int)$p['id']) ?>"><div><strong><?= e($p['pack_name']) ?></strong><span><?= e($p['search_name']) ?> · <?= number_format((int)$p['total_candidate_count']) ?> candidates</span></div><span class="cm-status cm-status--<?= e(cm_status_class($p['status'])) ?>"><?= e(cm_label($p['status'])) ?></span></a><?php endforeach; ?></div><?php endif; ?></section>
<section class="cm-card"><div class="cm-card__header"><div><h3>Privacy Controls</h3><p>Applied to every pack.</p></div></div><div class="cm-principles"><div><i class="fas fa-link"></i><strong>Same saved search</strong><span>Totals and breakdowns come from one immutable snapshot.</span></div><div><i class="fas fa-eye-slash"></i><strong>Small groups suppressed</strong><span>Exact values below threshold are not disclosed.</span></div><div><i class="fas fa-clock"></i><strong>Currency shown</strong><span>Data freshness and verification are visible.</span></div></div></section></div>
<?php require __DIR__.'/_layout_end.php'; ?>