<?php
require_once __DIR__.'/../includes/bootstrap.php';require_role('commercial_manager');$user=current_user();$flashes=render_flashes();$currentPage='generate_pack';$pageTitle='Generate Capability Pack';require_once __DIR__.'/_helpers.php';$conn=Database::getConnection();$managerId=(int)($user['id']??$user['user_id']??0);$sid=(int)($_GET['saved_search_id']??$_POST['saved_search_id']??0);
$s=$conn->prepare("SELECT * FROM commercial_saved_searches WHERE id=? AND commercial_manager_id=? LIMIT 1");$s->bind_param('ii',$sid,$managerId);$s->execute();$search=$s->get_result()->fetch_assoc();$s->close();if(!$search){http_response_code(403);exit('Saved search not found.');}$threshold=cm_threshold($conn);
if($_SERVER['REQUEST_METHOD']==='POST'){cm_verify_csrf();$name=trim((string)($_POST['pack_name']??''));$ref=trim((string)($_POST['tender_reference']??''));$client=trim((string)($_POST['client_name']??''));if($name===''){cm_flash('danger','Pack name is required.');header('Location: '.url('commercial_manager/generate_pack.php?saved_search_id='.$sid));exit;}
$conn->begin_transaction();try{$count=(int)$search['result_count'];$criteria=(string)$search['criteria_json'];$tax=(string)$search['taxonomy_version'];$snap=(string)$search['data_snapshot_at'];$s=$conn->prepare("INSERT INTO commercial_capability_packs(commercial_manager_id,saved_search_id,pack_name,tender_reference,client_name,status,total_candidate_count,criteria_snapshot_json,taxonomy_version,data_snapshot_at,suppression_threshold,generated_at) VALUES(?,?,?,?,?,'generated',?,?,?,?,?,NOW())");$s->bind_param('iisssisssi',$managerId,$sid,$name,$ref,$client,$count,$criteria,$tax,$snap,$threshold);$s->execute();$pid=$s->insert_id;$s->close();
$s=$conn->prepare("SELECT * FROM commercial_saved_search_breakdowns WHERE saved_search_id=?");$s->bind_param('i',$sid);$s->execute();$rr=$s->get_result();$suppressed=0;$ins=$conn->prepare("INSERT INTO commercial_capability_pack_breakdowns(capability_pack_id,dimension_name,dimension_value,displayed_value,raw_candidate_count,raw_verified_count,verification_rate,data_currency_label,is_suppressed) VALUES(?,?,?,?,?,?,?,?,?)");
while($row=$rr->fetch_assoc()){$c=(int)$row['candidate_count'];$v=(int)$row['verified_count'];$sup=$c>0&&$c<$threshold?1:0;if($sup)$suppressed++;$display=$sup?'<'.$threshold:(string)$c;$rate=$c>0?round(($v/$c)*100,2):0;$currency=cm_currency($row['most_recent_verification_at']);$ins->bind_param('isssiidsi',$pid,$row['dimension_name'],$row['dimension_value'],$display,$c,$v,$rate,$currency,$sup);$ins->execute();}$ins->close();$s->close();
$u=$conn->prepare("UPDATE commercial_capability_packs SET suppressed_group_count=? WHERE id=? AND commercial_manager_id=?");$u->bind_param('iii',$suppressed,$pid,$managerId);$u->execute();$u->close();$conn->commit();cm_activity($conn,$managerId,'capability_pack_generated','Generated anonymised tender capability pack.','capability_pack',$pid);cm_flash('success','Capability pack generated successfully.');header('Location: '.url('commercial_manager/pack_view.php?id='.$pid));exit;}catch(Throwable $e){$conn->rollback();cm_flash('danger','Pack generation failed; no partial pack was saved.');header('Location: '.url('commercial_manager/generate_pack.php?saved_search_id='.$sid));exit;}}
require __DIR__.'/_layout_start.php';?>
<div class="cm-page-header"><div><span>Tender Pack Generator</span><h2><?= e($search['search_name']) ?></h2><p><?= number_format((int)$search['result_count']) ?> candidates · suppression &lt;<?= $threshold ?></p></div></div>
<div class="cm-grid"><section class="cm-card"><div class="cm-card__header"><h3>Pack Details</h3></div><form method="post" class="cm-form"><input type="hidden" name="csrf_token" value="<?= e(cm_csrf()) ?>"><input type="hidden" name="saved_search_id" value="<?= $sid ?>"><label>Capability Pack Name<input name="pack_name" required placeholder="Java & Cloud Capability - Gauteng"></label><label>Tender Reference<input name="tender_reference" placeholder="RFP-2026-104"></label><label>Client / Buyer<input name="client_name" placeholder="Client organisation"></label><button class="cm-btn cm-btn--primary"><i class="fas fa-file-shield"></i> Generate Anonymised Pack</button></form></section><section class="cm-card"><div class="cm-card__header"><h3>Privacy Preview</h3></div><div class="cm-principles"><div><i class="fas fa-user-secret"></i><strong>No direct identifiers</strong><span>Names, email, phone, IDs and profile links are excluded.</span></div><div><i class="fas fa-eye-slash"></i><strong>Small groups suppressed</strong><span>Counts below <?= $threshold ?> are shown as &lt;<?= $threshold ?>.</span></div></div></section></div>
<?php require __DIR__.'/_layout_end.php';?>