<?php
require_once __DIR__.'/../includes/bootstrap.php';require_role('commercial_manager');$user=current_user();$flashes=render_flashes();$currentPage='pack_view';$pageTitle='Capability Pack';require_once __DIR__.'/_helpers.php';$conn=Database::getConnection();$managerId=(int)($user['id']??$user['user_id']??0);$id=(int)($_GET['id']??0);
$s=$conn->prepare("SELECT cp.*,ss.search_name,ss.source_search_reference FROM commercial_capability_packs cp JOIN commercial_saved_searches ss ON ss.id=cp.saved_search_id WHERE cp.id=? AND cp.commercial_manager_id=? LIMIT 1");$s->bind_param('ii',$id,$managerId);$s->execute();$pack=$s->get_result()->fetch_assoc();$s->close();if(!$pack){http_response_code(403);exit('Capability pack not found.');}
$rows=[];$s=$conn->prepare("SELECT * FROM commercial_capability_pack_breakdowns WHERE capability_pack_id=? ORDER BY dimension_name,raw_candidate_count DESC");$s->bind_param('i',$id);$s->execute();$r=$s->get_result();while($x=$r->fetch_assoc())$rows[]=$x;$s->close();$by=[];foreach($rows as $x)$by[$x['dimension_name']][]=$x;$criteria=cm_json($pack['criteria_snapshot_json']);
require __DIR__.'/_layout_start.php';?>
<div class="cm-print-actions"><a class="cm-btn cm-btn--secondary" href="<?= url('commercial_manager/capability_packs.php') ?>"><i class="fas fa-arrow-left"></i> Back</a><button class="cm-btn cm-btn--primary" onclick="window.print()"><i class="fas fa-print"></i> Print / Save PDF</button></div>
<article class="cm-document"><header><div><span>Investhood IT Programme & Scarce Skills Platform</span><h2><?= e($pack['pack_name']) ?></h2><p>Anonymised Tender Capability Pack</p></div><div><span>Tender Reference</span><strong><?= e($pack['tender_reference']?:'Not specified') ?></strong></div></header>
<section class="cm-document__summary"><div><span>Total Capacity</span><strong><?= number_format((int)$pack['total_candidate_count']) ?></strong></div><div><span>Taxonomy</span><strong><?= e($pack['taxonomy_version']) ?></strong></div><div><span>Data Snapshot</span><strong><?= e(cm_date($pack['data_snapshot_at'])) ?></strong></div><div><span>Currency</span><strong><?= e(cm_currency($pack['data_snapshot_at'])) ?></strong></div></section>
<section><h3>01 · Saved Search & Reconciliation</h3><div class="cm-detail-grid"><div><span>Saved Search</span><strong><?= e($pack['search_name']) ?></strong></div><div><span>Source</span><strong><?= e($pack['source_search_reference']?:'Internal saved search') ?></strong></div><div><span>Reconciled Count</span><strong><?= number_format((int)$pack['total_candidate_count']) ?></strong></div></div></section>
<section><h3>02 · Search Criteria</h3><div class="cm-detail-grid"><?php foreach($criteria as $k=>$v):?><div><span><?= e(cm_label((string)$k)) ?></span><strong><?= e(is_array($v)?implode(', ',$v):(string)$v) ?></strong></div><?php endforeach;?></div></section>
<section><h3>03 · Capability & Verification Breakdown</h3><?php foreach($by as $dim=>$items):?><h4><?= e(cm_label($dim)) ?></h4><div class="cm-table-wrap"><table><thead><tr><th>Group</th><th>Capacity</th><th>Verification</th><th>Currency</th></tr></thead><tbody><?php foreach($items as $x):?><tr><td><?= (int)$x['is_suppressed']?'Suppressed group':e($x['dimension_value']) ?></td><td><?= e($x['displayed_value']) ?></td><td><?= (int)$x['is_suppressed']?'Suppressed':number_format((float)$x['verification_rate'],1).'%' ?></td><td><?= e($x['data_currency_label']) ?></td></tr><?php endforeach;?></tbody></table></div><?php endforeach;?></section>
<section><h3>04 · Privacy Controls</h3><div class="cm-principles"><div><i class="fas fa-user-secret"></i><strong>Direct identifiers excluded</strong><span>No names, email, phone, identity numbers or direct profile links.</span></div><div><i class="fas fa-eye-slash"></i><strong>Small groups suppressed</strong><span>Counts below <?= (int)$pack['suppression_threshold'] ?> are not disclosed precisely.</span></div><div><i class="fas fa-clock"></i><strong>Data currency declared</strong><span>Snapshot dated <?= e(cm_date($pack['data_snapshot_at'])) ?>.</span></div></div></section>
<footer><span>Generated <?= e(cm_datetime($pack['generated_at'])) ?></span><span>Confidential · Anonymised Commercial Capability Evidence</span></footer></article>
<?php require __DIR__.'/_layout_end.php';?>