<?php
if (!function_exists('as_label')) { function as_label(?string $v): string { $v=trim((string)$v); return $v===''?'Unknown':ucwords(str_replace('_',' ',$v)); } }
if (!function_exists('as_class')) { function as_class(?string $v): string { return match(strtolower(trim((string)$v))){'competent','approved','completed','final_approved'=>'success','not_yet_competent','rejected','failed'=>'danger','pending','submitted','awaiting_moderation','in_review'=>'warning','changes_requested','resubmission_required'=>'purple','draft'=>'neutral',default=>'info'}; } }
if (!function_exists('as_date')) { function as_date(?string $v,string $f='Not set'): string { if(!$v)return $f; $t=strtotime($v); return $t?date('d M Y',$t):$f; } }
if (!function_exists('as_datetime')) { function as_datetime(?string $v,string $f='Not available'): string { if(!$v)return $f; $t=strtotime($v); return $t?date('d M Y, H:i',$t):$f; } }
if (!function_exists('as_initials')) { function as_initials(string $f,string $l): string { $x=''; if($f!=='')$x.=strtoupper(substr($f,0,1)); if($l!=='')$x.=strtoupper(substr($l,0,1)); return $x?:'AS'; } }
if (!function_exists('as_has_table')) { function as_has_table(mysqli $c,string $t): bool { static $m=[]; if(isset($m[$t]))return $m[$t]; $s=$c->real_escape_string($t); $r=$c->query("SHOW TABLES LIKE '$s'"); return $m[$t]=(bool)($r&&$r->num_rows); } }
if (!function_exists('as_csrf')) { function as_csrf(): string { if(session_status()!==PHP_SESSION_ACTIVE)session_start(); if(empty($_SESSION['as_csrf']))$_SESSION['as_csrf']=bin2hex(random_bytes(32)); return $_SESSION['as_csrf']; } }
if (!function_exists('as_verify_csrf')) { function as_verify_csrf(): void { $a=(string)($_SESSION['as_csrf']??'');$b=(string)($_POST['csrf_token']??''); if($a===''||$b===''||!hash_equals($a,$b)){http_response_code(419);exit('Invalid or expired security token.');} } }
if (!function_exists('as_flash')) { function as_flash(string $type,string $message): void { if(session_status()!==PHP_SESSION_ACTIVE)session_start(); $_SESSION['as_flash']=['type'=>$type,'message'=>$message]; } }
if (!function_exists('as_render_flash')) { function as_render_flash(): string { if(session_status()!==PHP_SESSION_ACTIVE)session_start(); $f=$_SESSION['as_flash']??null;unset($_SESSION['as_flash']); if(!$f)return ''; $t=htmlspecialchars($f['type']??'info',ENT_QUOTES,'UTF-8');$m=htmlspecialchars($f['message']??'',ENT_QUOTES,'UTF-8'); return '<div class="as-alert as-alert--'.$t.'"><i class="fas fa-circle-info"></i><div>'.$m.'</div></div>'; } }
if (!function_exists('as_activity')) { function as_activity(mysqli $c,int $uid,string $action,string $desc,?string $etype=null,?int $eid=null): void { if($uid<=0||!as_has_table($c,'assessor_activity_log'))return; $ip=$_SERVER['REMOTE_ADDR']??null;$ua=substr((string)($_SERVER['HTTP_USER_AGENT']??''),0,255);$s=$c->prepare('INSERT INTO assessor_activity_log (assessor_id,action,description,entity_type,entity_id,ip_address,user_agent) VALUES (?,?,?,?,?,?,?)'); if(!$s)return;$s->bind_param('isssiss',$uid,$action,$desc,$etype,$eid,$ip,$ua);$s->execute();$s->close(); } }
if (!function_exists('as_percent')) { function as_percent(int $a,int $b): int { return $b<=0?0:max(0,min(100,(int)round(($a/$b)*100))); } }

if (!function_exists('as_notifications')) { function as_notifications(mysqli $c,int $uid,int $limit=6): array { if($uid<=0)return ['items'=>[],'unread'=>0,'available'=>false];$r=$c->query("SHOW TABLES LIKE 'notifications'");if(!$r||!$r->num_rows)return ['items'=>[],'unread'=>0,'available'=>false];$cols=[];$cr=$c->query("SHOW COLUMNS FROM notifications");while($cr&&$x=$cr->fetch_assoc())$cols[$x['Field']]=true;$uc=isset($cols['user_id'])?'user_id':(isset($cols['recipient_id'])?'recipient_id':null);$mc=isset($cols['message'])?'message':(isset($cols['body'])?'body':(isset($cols['description'])?'description':null));$tc=isset($cols['title'])?'title':null;$rc=isset($cols['is_read'])?'is_read':(isset($cols['read_at'])?'read_at':null);$dc=isset($cols['created_at'])?'created_at':null;if(!$uc||!$mc)return ['items'=>[],'unread'=>0,'available'=>false];$te=$tc?$tc:"'Notification'";$de=$dc?$dc:'NULL';$re=$rc==='is_read'?'is_read':($rc==='read_at'?'CASE WHEN read_at IS NULL THEN 0 ELSE 1 END':'1');$sql="SELECT id,$te AS title,$mc AS message,$de AS created_at,$re AS is_read FROM notifications WHERE $uc=? ORDER BY ".($dc?$dc:'id')." DESC LIMIT ?";$st=$c->prepare($sql);if(!$st)return ['items'=>[],'unread'=>0,'available'=>false];$st->bind_param('ii',$uid,$limit);$st->execute();$items=$st->get_result()->fetch_all(MYSQLI_ASSOC);$st->close();$unread=0;foreach($items as $n)if((int)($n['is_read']??1)===0)$unread++;return ['items'=>$items,'unread'=>$unread,'available'=>true]; } }
