<?php
$currentPage=$currentPage??''; if(!isset($user)||!is_array($user))$user=current_user();$f=trim((string)($user['first_name']??''));$l=trim((string)($user['last_name']??''));$name=trim((string)($user['full_name']??$user['fullname']??($f.' '.$l)))?:'Assessor';$initials=as_initials($f,$l);
if(!function_exists('as_nav')){function as_nav(string $c,$p):string{$p=is_array($p)?$p:[$p];return in_array($c,$p,true)?'as-nav__item--active':'';}}
?>
<aside class="as-sidebar" id="assessorSidebar"><div class="as-sidebar__brand"><div class="as-sidebar__logo"><i class="fas fa-scale-balanced"></i></div><div class="as-sidebar__brand-copy"><strong>Investhood IT</strong><span>Assessment Workspace</span></div><button class="as-sidebar__close" id="assessorSidebarClose" type="button"><i class="fas fa-xmark"></i></button></div>
<div class="as-profile"><div class="as-profile__avatar"><?= e($initials) ?><span class="as-profile__online"></span></div><div class="as-profile__copy"><strong><?= e($name) ?></strong><span>Assessor</span></div></div>
<nav class="as-nav"><div class="as-nav__group"><div class="as-nav__label">Main</div><a class="as-nav__item <?= as_nav($currentPage,'dashboard') ?>" href="<?= url('assessor/dashboard.php') ?>"><span class="as-nav__icon"><i class="fas fa-grid-2"></i></span><span>Dashboard</span></a></div>
<div class="as-nav__group"><div class="as-nav__label">Assessment</div><a class="as-nav__item <?= as_nav($currentPage,['assessments','review_assessment']) ?>" href="<?= url('assessor/assessments.php') ?>"><span class="as-nav__icon"><i class="fas fa-clipboard-check"></i></span><span>Assessment Queue</span></a><a class="as-nav__item <?= as_nav($currentPage,'evidence') ?>" href="<?= url('assessor/evidence.php') ?>"><span class="as-nav__icon"><i class="fas fa-folder-open"></i></span><span>Evidence Library</span></a><a class="as-nav__item <?= as_nav($currentPage,'decisions') ?>" href="<?= url('assessor/decisions.php') ?>"><span class="as-nav__icon"><i class="fas fa-gavel"></i></span><span>My Decisions</span></a></div>
<div class="as-nav__group"><div class="as-nav__label">Quality & Audit</div><a class="as-nav__item <?= as_nav($currentPage,'moderation') ?>" href="<?= url('assessor/moderation.php') ?>"><span class="as-nav__icon"><i class="fas fa-shield-halved"></i></span><span>Moderation Status</span></a><a class="as-nav__item <?= as_nav($currentPage,'reports') ?>" href="<?= url('assessor/reports.php') ?>"><span class="as-nav__icon"><i class="fas fa-chart-column"></i></span><span>Reports</span></a><a class="as-nav__item <?= as_nav($currentPage,'activity_log') ?>" href="<?= url('assessor/activity_log.php') ?>"><span class="as-nav__icon"><i class="fas fa-clock-rotate-left"></i></span><span>Activity Log</span></a></div>
<div class="as-nav__group"><div class="as-nav__label">Appearance</div><button type="button" class="as-theme-control" data-assessor-theme-toggle><span class="as-nav__icon"><i class="fas fa-moon" data-assessor-theme-icon></i></span><span>Dark Mode</span><span class="as-theme-switch"></span></button></div></nav>
<div class="as-sidebar__footer"><div class="as-secure-card"><i class="fas fa-fingerprint"></i><div><strong>Audit Ready</strong><span>Every assessment decision is traceable.</span></div></div><a class="as-logout" href="<?= url('auth/logout.php') ?>"><i class="fas fa-arrow-right-from-bracket"></i><span>Sign Out</span></a></div></aside><div class="as-overlay" id="assessorOverlay"></div>
