<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
require_role('programme_officer');
require_once __DIR__ . '/_helpers.php';
header('Content-Type: application/json; charset=utf-8');
function po_chat_json(array $d,int $status=200):never{http_response_code($status);echo json_encode($d,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function po_chat_count(mysqli $c,string $sql,int $id):int{$s=$c->prepare($sql);if(!$s)throw new RuntimeException('Database prepare error: '.$c->error);$s->bind_param('i',$id);$s->execute();$r=$s->get_result()->fetch_assoc()?:[];$s->close();return(int)($r['total']??0);}
function po_chat_scope(mysqli $c,int $id):array{$scope=po_scope($c,'p','c');$mode=po_scope_mode($scope);return[$scope,$mode,po_scope_condition($scope)];}
function po_chat_reply(mysqli $c,int $id,string $q):array{[$scope,$mode,$where]=po_chat_scope($c,$id);if($mode==='none')return['message'=>'No Programme Officer data scope is currently available to your account.','action'=>['label'=>'Open Dashboard','url'=>url('programme_officer/dashboard.php')]];$l=strtolower(trim($q));$programmes=po_chat_count($c,"SELECT COUNT(DISTINCT p.id) total FROM programmes p LEFT JOIN cohorts c ON c.programme_id=p.id WHERE {$where}",$id);$cohorts=po_chat_count($c,"SELECT COUNT(DISTINCT c.id) total FROM programmes p INNER JOIN cohorts c ON c.programme_id=p.id WHERE {$where}",$id);$candidates=po_chat_count($c,"SELECT COUNT(DISTINCT CASE WHEN cp.status <> 'withdrawn' THEN cp.user_id END) total FROM programmes p LEFT JOIN cohorts c ON c.programme_id=p.id LEFT JOIN cohort_participants cp ON cp.cohort_id=c.id WHERE {$where}",$id);$active=po_chat_count($c,"SELECT COUNT(DISTINCT CASE WHEN cp.status='active' THEN cp.user_id END) total FROM programmes p LEFT JOIN cohorts c ON c.programme_id=p.id LEFT JOIN cohort_participants cp ON cp.cohort_id=c.id WHERE {$where}",$id);$completed=po_chat_count($c,"SELECT COUNT(DISTINCT CASE WHEN cp.status='completed' THEN cp.user_id END) total FROM programmes p LEFT JOIN cohorts c ON c.programme_id=p.id LEFT JOIN cohort_participants cp ON cp.cohort_id=c.id WHERE {$where}",$id);$rate=$candidates>0?(int)round(($completed/$candidates)*100):0;if(str_contains($l,'completion')||str_contains($l,'progress'))return['message'=>"Your current candidate completion rate is {$rate}% ({$completed} completed out of {$candidates} non-withdrawn candidates).",'action'=>['label'=>'View Programme Reports','url'=>url('programme_officer/reports.php')]];if(str_contains($l,'cohort'))return['message'=>"You currently have {$cohorts} cohort(s) across your assigned programme portfolio.",'action'=>['label'=>'View My Cohorts','url'=>url('programme_officer/cohorts.php')]];if(str_contains($l,'candidate')||str_contains($l,'participant'))return['message'=>"Your portfolio currently contains {$candidates} non-withdrawn candidate(s), including {$active} active and {$completed} completed.",'action'=>['label'=>'View Candidates','url'=>url('programme_officer/candidates.php')]];if(str_contains($l,'programme')||str_contains($l,'program'))return['message'=>"You currently have {$programmes} programme(s) in your Programme Officer scope.",'action'=>['label'=>'View My Programmes','url'=>url('programme_officer/programmes.php')]];if(str_contains($l,'active'))return['message'=>"There are {$active} active candidate(s) in your programme portfolio.",'action'=>['label'=>'View Active Candidates','url'=>url('programme_officer/candidates.php?status=active')]];return['message'=>"I can help with your {$programmes} programme(s), {$cohorts} cohort(s), {$candidates} candidate(s), active candidates and completion progress.",'action'=>['label'=>'Open Programme Officer Dashboard','url'=>url('programme_officer/dashboard.php')]];}
try{$u=current_user();$id=(int)($u['id']??$u['user_id']??0);if($id<=0)po_chat_json(['ok'=>false,'message'=>'Invalid Programme Officer account.'],403);$p=json_decode(file_get_contents('php://input')?:'{}',true);$q=trim((string)($p['message']??$_POST['message']??''));if($q==='')po_chat_json(['ok'=>false,'message'=>'Please enter a question.'],422);if(strlen($q)>500)$q=substr($q,0,500);po_chat_json(['ok'=>true]+po_chat_reply(Database::getConnection(),$id,$q));}catch(Throwable $e){error_log('Programme Officer chatbot: '.$e->getMessage());po_chat_json(['ok'=>false,'message'=>'The assistant could not complete that request. Please try again.'],500);}
