<?php
require_once __DIR__.'/../includes/bootstrap.php'; require_role('recruiter'); $user=current_user();$flashes=render_flashes();$currentPage='dashboard';$pageTitle='Recruiter Dashboard';require_once __DIR__.'/_helpers.php';$conn=Database::getConnection();$recruiterId=(int)($user['id']??$user['user_id']??0);if($recruiterId<=0){http_response_code(403);exit('Invalid Recruiter account.');}
$stats=['verified'=>0,'consented'=>0,'scarce'=>0,'gauteng'=>0,'shortlists'=>0];
if(rc_has_table($conn,'candidate_profiles')&&rc_has_table($conn,'candidate_consents')){$r=$conn->query("SELECT COUNT(DISTINCT CASE WHEN cp.verification_status='verified' THEN cp.user_id END) verified,COUNT(DISTINCT CASE WHEN cc.status='consented' AND (cc.expires_at IS NULL OR cc.expires_at>NOW()) THEN cp.user_id END) consented,COUNT(DISTINCT CASE WHEN cp.province='Gauteng' THEN cp.user_id END) gauteng FROM candidate_profiles cp LEFT JOIN candidate_consents cc ON cc.candidate_id=cp.user_id AND cc.consent_type='recruiter_discovery'");if($r)$stats=array_merge($stats,$r->fetch_assoc()?:[]);} if(rc_has_table($conn,'candidate_skills')&&rc_has_table($conn,'skills')){$r=$conn->query("SELECT COUNT(DISTINCT cs.candidate_id) scarce FROM candidate_skills cs JOIN skills s ON s.id=cs.skill_id WHERE s.is_scarce=1 AND cs.verification_status='verified'");if($r)$stats['scarce']=(int)($r->fetch_assoc()['scarce']??0);} if(rc_has_table($conn,'recruiter_shortlists')){$s=$conn->prepare("SELECT COUNT(*) total FROM recruiter_shortlists WHERE recruiter_id=?");$s->bind_param('i',$recruiterId);$s->execute();$stats['shortlists']=(int)($s->get_result()->fetch_assoc()['total']??0);$s->close();}
$f=trim((string)($user['first_name']??'Recruiter'));$taxonomy=rc_taxonomy_version($conn);require __DIR__.'/_layout_start.php';?>
<section class="rc-hero"><div><span class="rc-eyebrow"><i class="fas fa-bolt"></i> Scarce Skills Discovery</span><h2>Find verified talent faster, <?=e($f?:'Recruiter')?>.</h2><p>Search consented candidates using structured skill, location, verification and recency filters, then preserve your criteria and taxonomy version with every shortlist.</p><div class="rc-hero__actions"><a class="rc-btn rc-btn--light" href="<?=url('recruiter/search.php')?>"><i class="fas fa-magnifying-glass"></i> Find Candidates</a><a class="rc-btn rc-btn--glass" href="<?=url('recruiter/shortlists.php')?>"><i class="fas fa-list-check"></i> Open Shortlists</a></div></div><div class="rc-taxonomy"><span>Active Taxonomy</span><strong><?=e($taxonomy)?></strong><small>Matching decisions remain reproducible.</small></div></section>
<section class="rc-stats"><article><i class="fas fa-badge-check"></i><strong><?=number_format((int)$stats['verified'])?></strong><span>Verified Candidates</span></article><article><i class="fas fa-user-shield"></i><strong><?=number_format((int)$stats['consented'])?></strong><span>Consent Eligible</span></article><article><i class="fas fa-gem"></i><strong><?=number_format((int)$stats['scarce'])?></strong><span>Scarce Skill Profiles</span></article><article><i class="fas fa-location-dot"></i><strong><?=number_format((int)$stats['gauteng'])?></strong><span>Gauteng Candidates</span></article><article><i class="fas fa-list-check"></i><strong><?=number_format((int)$stats['shortlists'])?></strong><span>My Shortlists</span></article></section>
<div class="rc-grid"><a class="rc-action" href="<?=url('recruiter/search.php?skill=Java&province=Gauteng&verification=verified&scarce_only=1')?>"><i class="fab fa-java"></i><div><strong>Java in Gauteng</strong><span>Verified + scarce skill filter</span></div></a><a class="rc-action" href="<?=url('recruiter/search.php?skill=AWS&province=Gauteng&verification=verified&scarce_only=1')?>"><i class="fas fa-cloud"></i><div><strong>Cloud Talent</strong><span>Find verified cloud candidates</span></div></a><a class="rc-action" href="<?=url('recruiter/shortlists.php')?>"><i class="fas fa-list-check"></i><div><strong>Client Shortlists</strong><span>Open stored search contexts</span></div></a></div>
<div class="rc-card"><div class="rc-card__body rc-info"><i class="fas fa-shield-halved"></i><div><strong>Scope and consent are enforced before discovery.</strong><p>Candidate search is designed to return only recruiter-discovery consented candidates that satisfy the selected filters.</p></div></div></div>
<?php require __DIR__.'/_layout_end.php';?>