<?php
require_once __DIR__ . '/../includes/bootstrap.php';require_role('supervisor');require_once __DIR__ . '/_helpers.php';
$user=current_user();$flashes=render_flashes();$currentPage='activity_log';$pageTitle='Activity Log';$supervisorId=(int)($user['id']??$user['user_id']??0);if($supervisorId<=0){http_response_code(403);exit('Invalid Supervisor account.');}
$conn=Database::getConnection();$tableAvailable=false;$check=$conn->query("SHOW TABLES LIKE 'supervisor_activity_log'");if($check&&$check->num_rows>0)$tableAvailable=true;
$rows=[];$search=trim((string)($_GET['search']??''));$action=trim((string)($_GET['action']??''));$page=max(1,(int)($_GET['page']??1));$perPage=15;$total=0;$actions=[];
if($tableAvailable){$stmt=Database::prepare("SELECT DISTINCT action FROM supervisor_activity_log WHERE supervisor_id=? ORDER BY action",'i',[$supervisorId]);$r=$stmt->get_result();while($x=$r->fetch_assoc())$actions[]=$x['action'];$stmt->close();$where=['supervisor_id=?'];$types='i';$params=[$supervisorId];if($search!==''){$where[]='(action LIKE ? OR description LIKE ?)';$like='%'.$search.'%';$types.='ss';$params[]=$like;$params[]=$like;}if($action!==''){$where[]='action=?';$types.='s';$params[]=$action;}$stmt=Database::prepare("SELECT COUNT(*) total FROM supervisor_activity_log WHERE ".implode(' AND ',$where),$types,$params);$total=(int)(($stmt->get_result()->fetch_assoc()['total']??0));$stmt->close();$offset=($page-1)*$perPage;$query="SELECT id,action,description,entity_type,entity_id,ip_address,created_at FROM supervisor_activity_log WHERE ".implode(' AND ',$where)." ORDER BY created_at DESC,id DESC LIMIT ".$perPage." OFFSET ".$offset;$stmt=Database::prepare($query,$types,$params);$r=$stmt->get_result();while($x=$r->fetch_assoc())$rows[]=$x;$stmt->close();}
$pages=max(1,(int)ceil($total/$perPage));
require __DIR__ . '/_layout_start.php';
?>
<div class="sv-page-header"><div><span class="sv-eyebrow">Audit & Accountability</span><h2>Activity Log</h2><p>Review actions recorded against your Supervisor account.</p></div></div>
<?php if(!$tableAvailable): ?><div class="sv-security" style="background:var(--sv-orange-soft);border-color:rgba(217,119,6,.18)"><i class="fas fa-triangle-exclamation" style="color:var(--sv-orange)"></i><div><strong>Activity table not installed</strong><p>Run the included <code>supervisor_portal.sql</code> migration. The page is intentionally showing this message instead of failing with a database exception.</p></div></div><?php else: ?>
<section class="sv-stats"><article class="sv-stat"><div class="sv-stat__icon sv-stat__icon--blue"><i class="fas fa-clock-rotate-left"></i></div><strong><?= $total ?></strong><span>Matching Activities</span></article><article class="sv-stat"><div class="sv-stat__icon sv-stat__icon--green"><i class="fas fa-calendar-day"></i></div><strong><?= count(array_filter($rows,fn($x)=>date('Y-m-d',strtotime($x['created_at']))===date('Y-m-d'))) ?></strong><span>Shown Today</span></article><article class="sv-stat"><div class="sv-stat__icon sv-stat__icon--purple"><i class="fas fa-filter"></i></div><strong><?= count($actions) ?></strong><span>Action Types</span></article><article class="sv-stat"><div class="sv-stat__icon sv-stat__icon--orange"><i class="fas fa-shield-halved"></i></div><strong>Scoped</strong><span>Supervisor Audit</span></article></section>
<form class="sv-filter" method="get"><div class="sv-filter-grid"><div class="sv-field"><label>Search</label><input class="sv-input" name="search" value="<?= e($search) ?>" placeholder="Action or description"></div><div class="sv-field"><label>Action</label><select class="sv-select" name="action"><option value="">All actions</option><?php foreach($actions as $a): ?><option value="<?= e($a) ?>" <?= $action===$a?'selected':'' ?>><?= e(sv_status_label($a)) ?></option><?php endforeach; ?></select></div><div class="sv-filter-actions"><button class="sv-btn sv-btn--primary"><i class="fas fa-filter"></i> Apply</button><a class="sv-btn sv-btn--secondary" href="<?= url('supervisor/activity_log.php') ?>">Reset</a></div></div></form>
<section class="sv-card"><div class="sv-card__header"><div><h3>Recorded Activity</h3><p>Newest activity appears first.</p></div></div><?php if(!$rows): ?><div class="sv-empty"><i class="fas fa-clock-rotate-left"></i><strong>No activity found</strong><span>No records match the current filters.</span></div><?php else: ?><div class="sv-table-wrap"><table class="sv-table"><thead><tr><th>Action</th><th>Description</th><th>Entity</th><th>IP</th><th>Date</th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td><strong><?= e(sv_status_label($row['action'])) ?></strong></td><td><?= e($row['description']) ?></td><td><?= e((string)($row['entity_type']??'—')) ?><?= !empty($row['entity_id'])?' #'.(int)$row['entity_id']:'' ?></td><td><?= e((string)($row['ip_address']??'—')) ?></td><td><?= e(sv_datetime($row['created_at'])) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?><?php if($pages>1): ?><div class="sv-pagination"><span>Page <?= $page ?> of <?= $pages ?></span><div class="sv-pagination__actions"><?php if($page>1): ?><a class="sv-btn sv-btn--secondary" href="<?= e(sv_query_url(['page'=>$page-1])) ?>">Previous</a><?php endif; ?><?php if($page<$pages): ?><a class="sv-btn sv-btn--secondary" href="<?= e(sv_query_url(['page'=>$page+1])) ?>">Next</a><?php endif; ?></div></div><?php endif; ?></section>
<?php endif; ?>
<?php require __DIR__ . '/_layout_end.php'; ?>
