<?php
require_once __DIR__ . '/../includes/bootstrap.php';require_role('supervisor');require_once __DIR__ . '/_helpers.php';
$user=current_user();$flashes=render_flashes();$currentPage='candidates';$pageTitle='Candidates';$supervisorId=(int)($user['id']??$user['user_id']??0);if($supervisorId<=0){http_response_code(403);exit('Invalid Supervisor account.');}
$search=trim((string)($_GET['search']??''));$status=trim((string)($_GET['status']??''));$cohortId=(int)($_GET['cohort_id']??0);
$stmt=Database::prepare("SELECT c.id,c.name FROM cohorts c WHERE c.supervisor_id=? ORDER BY c.name",'i',[$supervisorId]);$cohorts=[];$r=$stmt->get_result();while($x=$r->fetch_assoc())$cohorts[]=$x;$stmt->close();
$where=['c.supervisor_id=?'];$types='i';$params=[$supervisorId];if($search!==''){$where[]='(u.first_name LIKE ? OR u.last_name LIKE ? OR u.email LIKE ?)';$like='%'.$search.'%';$types.='sss';array_push($params,$like,$like,$like);}if($status!==''){$where[]='cp.status=?';$types.='s';$params[]=$status;}if($cohortId>0){$where[]='c.id=?';$types.='i';$params[]=$cohortId;}
$stmt=Database::prepare("SELECT cp.id participation_id,u.id candidate_id,u.first_name,u.last_name,u.email,cp.status participant_status,cp.selected_at,cp.onboarded_at,cp.completed_at,c.id cohort_id,c.name cohort_name,p.name programme_name FROM cohort_participants cp JOIN cohorts c ON c.id=cp.cohort_id JOIN programmes p ON p.id=c.programme_id JOIN users u ON u.id=cp.user_id WHERE ".implode(' AND ',$where)." ORDER BY u.first_name,u.last_name",$types,$params);$rows=[];$r=$stmt->get_result();while($x=$r->fetch_assoc())$rows[]=$x;$stmt->close();
require __DIR__ . '/_layout_start.php';
?>
<div class="sv-page-header"><div><span class="sv-eyebrow">Candidate Monitoring</span><h2>Candidates</h2><p>Review participants in your assigned cohorts and open a candidate record to inspect or update participation status.</p></div></div>
<section class="sv-stats"><article class="sv-stat"><div class="sv-stat__icon sv-stat__icon--blue"><i class="fas fa-users"></i></div><strong><?= count($rows) ?></strong><span>Matching Candidates</span></article><article class="sv-stat"><div class="sv-stat__icon sv-stat__icon--green"><i class="fas fa-play"></i></div><strong><?= count(array_filter($rows,fn($x)=>$x['participant_status']==='active')) ?></strong><span>Active</span></article><article class="sv-stat"><div class="sv-stat__icon sv-stat__icon--purple"><i class="fas fa-circle-check"></i></div><strong><?= count(array_filter($rows,fn($x)=>$x['participant_status']==='completed')) ?></strong><span>Completed</span></article><article class="sv-stat"><div class="sv-stat__icon sv-stat__icon--red"><i class="fas fa-user-minus"></i></div><strong><?= count(array_filter($rows,fn($x)=>$x['participant_status']==='withdrawn')) ?></strong><span>Withdrawn</span></article></section>
<form class="sv-filter" method="get"><div class="sv-filter-grid"><div class="sv-field"><label>Search candidate</label><input class="sv-input" name="search" value="<?= e($search) ?>" placeholder="Name or email"></div><div class="sv-field"><label>Cohort</label><select class="sv-select" name="cohort_id"><option value="0">All cohorts</option><?php foreach($cohorts as $c): ?><option value="<?= (int)$c['id'] ?>" <?= $cohortId===(int)$c['id']?'selected':'' ?>><?= e($c['name']) ?></option><?php endforeach; ?></select></div><div class="sv-field"><label>Status</label><select class="sv-select" name="status"><option value="">All statuses</option><?php foreach(['active','completed','withdrawn'] as $s): ?><option value="<?= e($s) ?>" <?= $status===$s?'selected':'' ?>><?= e(sv_status_label($s)) ?></option><?php endforeach; ?></select></div><div class="sv-filter-actions"><button class="sv-btn sv-btn--primary"><i class="fas fa-filter"></i> Apply</button><a class="sv-btn sv-btn--secondary" href="<?= url('supervisor/candidates.php') ?>">Reset</a></div></div></form>
<section class="sv-card"><div class="sv-card__header"><div><h3>Candidate Directory</h3><p>Scoped to your assigned cohorts.</p></div></div><?php if(!$rows): ?><div class="sv-empty"><i class="fas fa-users"></i><strong>No candidates found</strong><span>Try another filter or cohort.</span></div><?php else: ?><div class="sv-table-wrap"><table class="sv-table"><thead><tr><th>Candidate</th><th>Programme</th><th>Cohort</th><th>Status</th><th>Selected</th><th></th></tr></thead><tbody><?php foreach($rows as $row):$fn=trim((string)$row['first_name']);$ln=trim((string)$row['last_name']);?><tr><td><div class="sv-person"><div class="sv-avatar"><?= e(sv_initials($fn,$ln)) ?></div><div class="sv-person__copy"><strong><?= e(trim($fn.' '.$ln) ?: 'Candidate') ?></strong><span><?= e((string)$row['email']) ?></span></div></div></td><td><?= e($row['programme_name']) ?></td><td><?= e($row['cohort_name']) ?></td><td><span class="sv-status sv-status--<?= e(sv_status_class($row['participant_status'])) ?>"><?= e(sv_status_label($row['participant_status'])) ?></span></td><td><?= e(sv_date($row['selected_at'])) ?></td><td><a class="sv-icon-btn" href="<?= url('supervisor/candidate_view.php?id='.(int)$row['candidate_id'].'&cohort_id='.(int)$row['cohort_id']) ?>"><i class="fas fa-eye"></i></a></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
<div class="sv-security"><i class="fas fa-shield-halved"></i><div><strong>Candidate access is cohort-scoped</strong><p>Candidate records are returned only through cohorts assigned to your Supervisor account.</p></div></div>
<?php require __DIR__ . '/_layout_end.php'; ?>
