<?php
require_once __DIR__ . '/../includes/bootstrap.php';require_role('supervisor');require_once __DIR__ . '/_helpers.php';
$user=current_user();$flashes=render_flashes();$currentPage='candidate_view';$pageTitle='Candidate Details';$supervisorId=(int)($user['id']??$user['user_id']??0);$candidateId=(int)($_GET['id']??0);$cohortId=(int)($_GET['cohort_id']??0);if($supervisorId<=0||$candidateId<=0){http_response_code(400);exit('Invalid request.');}
$sql="SELECT u.id candidate_id,u.first_name,u.last_name,u.email,cp.id participation_id,cp.status participant_status,cp.selected_at,cp.onboarded_at,cp.completed_at,c.id cohort_id,c.name cohort_name,c.start_date,c.end_date,p.name programme_name,p.type programme_type FROM cohort_participants cp JOIN cohorts c ON c.id=cp.cohort_id JOIN programmes p ON p.id=c.programme_id JOIN users u ON u.id=cp.user_id WHERE u.id=? AND c.supervisor_id=?";$types='ii';$params=[$candidateId,$supervisorId];if($cohortId>0){$sql.=' AND c.id=?';$types.='i';$params[]=$cohortId;}$sql.=' ORDER BY cp.id DESC LIMIT 1';$stmt=Database::prepare($sql,$types,$params);$candidate=$stmt->get_result()->fetch_assoc();$stmt->close();if(!$candidate){http_response_code(404);exit('Candidate not found in your assigned cohorts.');}
$fn=trim((string)$candidate['first_name']);$ln=trim((string)$candidate['last_name']);$name=trim($fn.' '.$ln)?:'Candidate';
require __DIR__ . '/_layout_start.php';
?>
<div class="sv-page-header"><div><span class="sv-eyebrow">Candidate Record</span><h2><?= e($name) ?></h2><p><?= e((string)$candidate['email']) ?> · <?= e($candidate['cohort_name']) ?></p></div><div class="sv-actions"><a class="sv-btn sv-btn--secondary" href="<?= url('supervisor/candidates.php') ?>"><i class="fas fa-arrow-left"></i> Back</a><?php if($candidate['participant_status']!=='withdrawn'): ?><a class="sv-btn sv-btn--primary" href="<?= url('supervisor/update_candidate_status.php?id='.(int)$candidate['candidate_id'].'&cohort_id='.(int)$candidate['cohort_id']) ?>"><i class="fas fa-pen"></i> Update Status</a><?php endif; ?></div></div>
<div class="sv-grid sv-grid--2"><section class="sv-card"><div class="sv-card__header"><div><h3>Candidate Profile</h3><p>Basic candidate information.</p></div></div><div class="sv-card__body"><div class="sv-person" style="margin-bottom:18px"><div class="sv-avatar" style="width:56px;height:56px;flex-basis:56px;font-size:14px"><?= e(sv_initials($fn,$ln)) ?></div><div class="sv-person__copy"><strong style="font-size:14px"><?= e($name) ?></strong><span><?= e((string)$candidate['email']) ?></span></div></div><p><strong>Programme:</strong> <?= e($candidate['programme_name']) ?></p><p><strong>Programme type:</strong> <?= e((string)$candidate['programme_type']) ?></p><p><strong>Cohort:</strong> <?= e($candidate['cohort_name']) ?></p><p><strong>Status:</strong> <span class="sv-status sv-status--<?= e(sv_status_class($candidate['participant_status'])) ?>"><?= e(sv_status_label($candidate['participant_status'])) ?></span></p></div></section><section class="sv-card"><div class="sv-card__header"><div><h3>Participation Timeline</h3><p>Recorded cohort milestones.</p></div></div><div class="sv-card__body"><p><strong>Selected:</strong> <?= e(sv_datetime($candidate['selected_at'])) ?></p><p><strong>Onboarded:</strong> <?= e(sv_datetime($candidate['onboarded_at'])) ?></p><p><strong>Completed:</strong> <?= e(sv_datetime($candidate['completed_at'])) ?></p><p><strong>Cohort period:</strong> <?= e(sv_date($candidate['start_date'])) ?> — <?= e(sv_date($candidate['end_date'])) ?></p></div></section></div>
<div class="sv-security"><i class="fas fa-shield-halved"></i><div><strong>Protected candidate record</strong><p>This page validates the candidate through a cohort assigned to your Supervisor account before displaying any information.</p></div></div>
<?php require __DIR__ . '/_layout_end.php'; ?>
