<?php
require_once __DIR__ . '/../includes/bootstrap.php';require_role('supervisor');require_once __DIR__ . '/_helpers.php';
$user=current_user();$flashes=render_flashes();$currentPage='cohort_view';$pageTitle='Cohort Details';$supervisorId=(int)($user['id']??$user['user_id']??0);$cohortId=(int)($_GET['id']??0);if($supervisorId<=0||$cohortId<=0){http_response_code(400);exit('Invalid request.');}
$stmt=Database::prepare("SELECT c.id,c.name cohort_name,c.status cohort_status,c.start_date,c.end_date,p.name programme_name,p.type programme_type,p.status programme_status FROM cohorts c JOIN programmes p ON p.id=c.programme_id WHERE c.id=? AND c.supervisor_id=? LIMIT 1",'ii',[$cohortId,$supervisorId]);$cohort=$stmt->get_result()->fetch_assoc();$stmt->close();if(!$cohort){http_response_code(404);exit('Cohort not found or not assigned to you.');}
$stmt=Database::prepare("SELECT u.id candidate_id,u.first_name,u.last_name,u.email,cp.status participant_status,cp.selected_at,cp.onboarded_at,cp.completed_at FROM cohort_participants cp JOIN users u ON u.id=cp.user_id JOIN cohorts c ON c.id=cp.cohort_id WHERE cp.cohort_id=? AND c.supervisor_id=? ORDER BY u.first_name,u.last_name",'ii',[$cohortId,$supervisorId]);$rows=[];$r=$stmt->get_result();while($x=$r->fetch_assoc())$rows[]=$x;$stmt->close();$total=count(array_filter($rows,fn($x)=>$x['participant_status']!=='withdrawn'));$completed=count(array_filter($rows,fn($x)=>$x['participant_status']==='completed'));$active=count(array_filter($rows,fn($x)=>$x['participant_status']==='active'));$rate=sv_completion_rate($total,$completed);
require __DIR__ . '/_layout_start.php';
?>
<div class="sv-page-header"><div><span class="sv-eyebrow">Assigned Cohort</span><h2><?= e($cohort['cohort_name']) ?></h2><p><?= e($cohort['programme_name']) ?> · <?= e(sv_date($cohort['start_date'])) ?> to <?= e(sv_date($cohort['end_date'])) ?></p></div><div class="sv-actions"><a class="sv-btn sv-btn--secondary" href="<?= url('supervisor/cohorts.php') ?>"><i class="fas fa-arrow-left"></i> Back</a></div></div>
<section class="sv-stats"><article class="sv-stat"><div class="sv-stat__icon sv-stat__icon--blue"><i class="fas fa-users"></i></div><strong><?= $total ?></strong><span>Current Candidates</span></article><article class="sv-stat"><div class="sv-stat__icon sv-stat__icon--green"><i class="fas fa-play"></i></div><strong><?= $active ?></strong><span>Active</span></article><article class="sv-stat"><div class="sv-stat__icon sv-stat__icon--purple"><i class="fas fa-circle-check"></i></div><strong><?= $completed ?></strong><span>Completed</span></article><article class="sv-stat"><div class="sv-stat__icon sv-stat__icon--orange"><i class="fas fa-chart-line"></i></div><strong><?= $rate ?>%</strong><span>Completion Rate</span></article></section>
<div class="sv-grid sv-grid--2" style="margin-bottom:18px"><section class="sv-card"><div class="sv-card__header"><div><h3>Cohort Information</h3><p>Programme and delivery details.</p></div></div><div class="sv-card__body"><p><strong>Status:</strong> <span class="sv-status sv-status--<?= e(sv_status_class($cohort['cohort_status'])) ?>"><?= e(sv_status_label($cohort['cohort_status'])) ?></span></p><p><strong>Programme:</strong> <?= e($cohort['programme_name']) ?></p><p><strong>Programme type:</strong> <?= e((string)$cohort['programme_type']) ?></p><p><strong>Start:</strong> <?= e(sv_date($cohort['start_date'])) ?></p><p><strong>End:</strong> <?= e(sv_date($cohort['end_date'])) ?></p></div></section><section class="sv-card"><div class="sv-card__header"><div><h3>Progress</h3><p>Completion across current participants.</p></div></div><div class="sv-card__body"><div class="sv-progress"><div class="sv-progress__meta"><span>Completed</span><strong><?= $rate ?>%</strong></div><div class="sv-progress__track"><div class="sv-progress__bar" style="width:<?= $rate ?>%"></div></div></div></div></section></div>
<section class="sv-card"><div class="sv-card__header"><div><h3>Participants</h3><p>Candidates currently associated with this cohort.</p></div></div><?php if(!$rows): ?><div class="sv-empty"><i class="fas fa-users"></i><strong>No participants</strong><span>This cohort has no participants yet.</span></div><?php else: ?><div class="sv-table-wrap"><table class="sv-table"><thead><tr><th>Candidate</th><th>Status</th><th>Selected</th><th>Onboarded</th><th>Completed</th><th></th></tr></thead><tbody><?php foreach($rows as $row):$fn=trim((string)$row['first_name']);$ln=trim((string)$row['last_name']);?><tr><td><div class="sv-person"><div class="sv-avatar"><?= e(sv_initials($fn,$ln)) ?></div><div class="sv-person__copy"><strong><?= e(trim($fn.' '.$ln) ?: 'Candidate') ?></strong><span><?= e((string)$row['email']) ?></span></div></div></td><td><span class="sv-status sv-status--<?= e(sv_status_class($row['participant_status'])) ?>"><?= e(sv_status_label($row['participant_status'])) ?></span></td><td><?= e(sv_date($row['selected_at'])) ?></td><td><?= e(sv_date($row['onboarded_at'])) ?></td><td><?= e(sv_date($row['completed_at'])) ?></td><td><a class="sv-icon-btn" href="<?= url('supervisor/candidate_view.php?id='.(int)$row['candidate_id'].'&cohort_id='.$cohortId) ?>"><i class="fas fa-eye"></i></a></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
<?php require __DIR__ . '/_layout_end.php'; ?>
