<?php
require_once __DIR__ . '/../includes/bootstrap.php';
require_role('supervisor');
require_once __DIR__ . '/_helpers.php';
$user=current_user();$flashes=render_flashes();$currentPage='cohorts';$pageTitle='My Cohorts';$supervisorId=(int)($user['id']??$user['user_id']??0);if($supervisorId<=0){http_response_code(403);exit('Invalid Supervisor account.');}
$search=trim((string)($_GET['search']??''));$status=trim((string)($_GET['status']??''));
$where=['c.supervisor_id = ?'];$types='i';$params=[$supervisorId];
if($search!==''){$where[]='(c.name LIKE ? OR p.name LIKE ?)';$like='%'.$search.'%';$types.='ss';$params[]=$like;$params[]=$like;}
if($status!==''){$where[]='c.status = ?';$types.='s';$params[]=$status;}
$stmt=Database::prepare("SELECT c.id,c.name cohort_name,c.status cohort_status,c.start_date,c.end_date,p.name programme_name,p.type programme_type,
 COUNT(DISTINCT CASE WHEN cp.status<>'withdrawn' THEN cp.user_id END) current_candidates,
 COUNT(DISTINCT CASE WHEN cp.status='completed' THEN cp.user_id END) completed_candidates
 FROM cohorts c JOIN programmes p ON p.id=c.programme_id LEFT JOIN cohort_participants cp ON cp.cohort_id=c.id WHERE ".implode(' AND ',$where)."
 GROUP BY c.id,c.name,c.status,c.start_date,c.end_date,p.name,p.type ORDER BY c.start_date DESC,c.id DESC",$types,$params);
$rows=[];$r=$stmt->get_result();while($row=$r->fetch_assoc()){$row['rate']=sv_completion_rate((int)$row['current_candidates'],(int)$row['completed_candidates']);$rows[]=$row;}$stmt->close();
$stmt=Database::prepare("SELECT COUNT(*) total,COUNT(CASE WHEN status='active' THEN 1 END) active FROM cohorts WHERE supervisor_id=?",'i',[$supervisorId]);$summary=$stmt->get_result()->fetch_assoc()?:[];$stmt->close();
require __DIR__ . '/_layout_start.php';
?>
<div class="sv-page-header"><div><span class="sv-eyebrow">Cohort Management</span><h2>My Cohorts</h2><p>Review the programmes and cohorts assigned to you, including participant volume and completion progress.</p></div></div>
<section class="sv-stats"><article class="sv-stat"><div class="sv-stat__icon sv-stat__icon--blue"><i class="fas fa-layer-group"></i></div><strong><?= number_format((int)($summary['total']??0)) ?></strong><span>Total Assigned</span></article><article class="sv-stat"><div class="sv-stat__icon sv-stat__icon--green"><i class="fas fa-bolt"></i></div><strong><?= number_format((int)($summary['active']??0)) ?></strong><span>Active Cohorts</span></article><article class="sv-stat"><div class="sv-stat__icon sv-stat__icon--purple"><i class="fas fa-users"></i></div><strong><?= number_format(array_sum(array_map(fn($x)=>(int)$x['current_candidates'],$rows))) ?></strong><span>Visible Candidates</span></article><article class="sv-stat"><div class="sv-stat__icon sv-stat__icon--orange"><i class="fas fa-chart-line"></i></div><strong><?= $rows ? (int)round(array_sum(array_column($rows,'rate'))/count($rows)) : 0 ?>%</strong><span>Average Completion</span></article></section>
<form class="sv-filter" method="get"><div class="sv-filter-grid"><div class="sv-field"><label>Search</label><input class="sv-input" name="search" value="<?= e($search) ?>" placeholder="Cohort or programme"></div><div class="sv-field"><label>Status</label><select class="sv-select" name="status"><option value="">All statuses</option><?php foreach(['active','completed','upcoming','inactive'] as $s): ?><option value="<?= e($s) ?>" <?= $status===$s?'selected':'' ?>><?= e(sv_status_label($s)) ?></option><?php endforeach; ?></select></div><div class="sv-filter-actions"><button class="sv-btn sv-btn--primary"><i class="fas fa-filter"></i> Apply</button><a class="sv-btn sv-btn--secondary" href="<?= url('supervisor/cohorts.php') ?>">Reset</a></div></div></form>
<section class="sv-card"><div class="sv-card__header"><div><h3>Assigned Cohorts</h3><p><?= number_format(count($rows)) ?> cohort(s) match your filters.</p></div></div>
<?php if(!$rows): ?><div class="sv-empty"><i class="fas fa-layer-group"></i><strong>No cohorts found</strong><span>Try changing your filters.</span></div><?php else: ?><div class="sv-table-wrap"><table class="sv-table"><thead><tr><th>Cohort</th><th>Status</th><th>Dates</th><th>Candidates</th><th>Progress</th><th></th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td><div class="sv-person"><div class="sv-avatar"><i class="fas fa-layer-group"></i></div><div class="sv-person__copy"><strong><?= e($row['cohort_name']) ?></strong><span><?= e($row['programme_name']) ?></span></div></div></td><td><span class="sv-status sv-status--<?= e(sv_status_class($row['cohort_status'])) ?>"><?= e(sv_status_label($row['cohort_status'])) ?></span></td><td><?= e(sv_date($row['start_date'])) ?> — <?= e(sv_date($row['end_date'])) ?></td><td><?= number_format((int)$row['current_candidates']) ?></td><td style="min-width:140px"><div class="sv-progress"><div class="sv-progress__meta"><span>Completed</span><strong><?= (int)$row['rate'] ?>%</strong></div><div class="sv-progress__track"><div class="sv-progress__bar" style="width:<?= (int)$row['rate'] ?>%"></div></div></div></td><td><a class="sv-icon-btn" href="<?= url('supervisor/cohort_view.php?id='.(int)$row['id']) ?>"><i class="fas fa-arrow-right"></i></a></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
<div class="sv-security"><i class="fas fa-shield-halved"></i><div><strong>Assignment boundary enforced</strong><p>Only cohorts where your user ID is recorded as the assigned Supervisor are returned.</p></div></div>
<?php require __DIR__ . '/_layout_end.php'; ?>
