<?php
require_once __DIR__ . '/../includes/bootstrap.php';require_role('supervisor');require_once __DIR__ . '/_helpers.php';
$user=current_user();$flashes=render_flashes();$currentPage='reports';$pageTitle='Cohort Progress';$supervisorId=(int)($user['id']??$user['user_id']??0);if($supervisorId<=0){http_response_code(403);exit('Invalid Supervisor account.');}
$programmeId=(int)($_GET['programme_id']??0);$cohortId=(int)($_GET['cohort_id']??0);$status=trim((string)($_GET['status']??''));
$stmt=Database::prepare("SELECT DISTINCT p.id,p.name FROM programmes p JOIN cohorts c ON c.programme_id=p.id WHERE c.supervisor_id=? ORDER BY p.name",'i',[$supervisorId]);$programmes=[];$r=$stmt->get_result();while($x=$r->fetch_assoc())$programmes[]=$x;$stmt->close();
$stmt=Database::prepare("SELECT id,name FROM cohorts WHERE supervisor_id=? ORDER BY name",'i',[$supervisorId]);$cohorts=[];$r=$stmt->get_result();while($x=$r->fetch_assoc())$cohorts[]=$x;$stmt->close();
$where=['c.supervisor_id=?'];$types='i';$params=[$supervisorId];if($programmeId>0){$where[]='p.id=?';$types.='i';$params[]=$programmeId;}if($cohortId>0){$where[]='c.id=?';$types.='i';$params[]=$cohortId;}if($status!==''){$where[]='cp.status=?';$types.='s';$params[]=$status;}
$stmt=Database::prepare("SELECT p.name programme_name,c.id cohort_id,c.name cohort_name,c.status cohort_status,c.start_date,c.end_date,
 COUNT(DISTINCT CASE WHEN cp.status<>'withdrawn' THEN cp.user_id END) total_candidates,
 COUNT(DISTINCT CASE WHEN cp.status='active' THEN cp.user_id END) active_candidates,
 COUNT(DISTINCT CASE WHEN cp.status='completed' THEN cp.user_id END) completed_candidates,
 COUNT(DISTINCT CASE WHEN cp.status='withdrawn' THEN cp.user_id END) withdrawn_candidates
 FROM cohorts c JOIN programmes p ON p.id=c.programme_id LEFT JOIN cohort_participants cp ON cp.cohort_id=c.id WHERE ".implode(' AND ',$where)." GROUP BY p.name,c.id,c.name,c.status,c.start_date,c.end_date ORDER BY p.name,c.name",$types,$params);$rows=[];$r=$stmt->get_result();while($x=$r->fetch_assoc()){$x['rate']=sv_completion_rate((int)$x['total_candidates'],(int)$x['completed_candidates']);$rows[]=$x;}$stmt->close();$total=array_sum(array_map(fn($x)=>(int)$x['total_candidates'],$rows));$completed=array_sum(array_map(fn($x)=>(int)$x['completed_candidates'],$rows));$active=array_sum(array_map(fn($x)=>(int)$x['active_candidates'],$rows));$withdrawn=array_sum(array_map(fn($x)=>(int)$x['withdrawn_candidates'],$rows));$overall=sv_completion_rate($total,$completed);
require __DIR__ . '/_layout_start.php';
?>
<div class="sv-page-header"><div><span class="sv-eyebrow">Reporting</span><h2>Cohort Progress</h2><p>Operational reporting for programmes, cohorts and participants assigned to you.</p></div></div>
<section class="sv-stats sv-stats--5"><article class="sv-stat"><div class="sv-stat__icon sv-stat__icon--blue"><i class="fas fa-layer-group"></i></div><strong><?= count($rows) ?></strong><span>Cohorts</span></article><article class="sv-stat"><div class="sv-stat__icon sv-stat__icon--orange"><i class="fas fa-users"></i></div><strong><?= $total ?></strong><span>Current Candidates</span></article><article class="sv-stat"><div class="sv-stat__icon sv-stat__icon--green"><i class="fas fa-play"></i></div><strong><?= $active ?></strong><span>Active</span></article><article class="sv-stat"><div class="sv-stat__icon sv-stat__icon--purple"><i class="fas fa-circle-check"></i></div><strong><?= $completed ?></strong><span>Completed</span></article><article class="sv-stat"><div class="sv-stat__icon sv-stat__icon--red"><i class="fas fa-chart-line"></i></div><strong><?= $overall ?>%</strong><span>Completion Rate</span></article></section>
<form class="sv-filter" method="get"><div class="sv-filter-grid"><div class="sv-field"><label>Programme</label><select class="sv-select" name="programme_id"><option value="0">All programmes</option><?php foreach($programmes as $p): ?><option value="<?= (int)$p['id'] ?>" <?= $programmeId===(int)$p['id']?'selected':'' ?>><?= e($p['name']) ?></option><?php endforeach; ?></select></div><div class="sv-field"><label>Cohort</label><select class="sv-select" name="cohort_id"><option value="0">All cohorts</option><?php foreach($cohorts as $c): ?><option value="<?= (int)$c['id'] ?>" <?= $cohortId===(int)$c['id']?'selected':'' ?>><?= e($c['name']) ?></option><?php endforeach; ?></select></div><div class="sv-field"><label>Candidate status</label><select class="sv-select" name="status"><option value="">All statuses</option><?php foreach(['active','completed','withdrawn'] as $s): ?><option value="<?= e($s) ?>" <?= $status===$s?'selected':'' ?>><?= e(sv_status_label($s)) ?></option><?php endforeach; ?></select></div><div class="sv-filter-actions"><button class="sv-btn sv-btn--primary"><i class="fas fa-filter"></i> Apply</button><a class="sv-btn sv-btn--secondary" href="<?= url('supervisor/reports.php') ?>">Reset</a></div></div></form>
<section class="sv-card"><div class="sv-card__header"><div><h3>Progress by Cohort</h3><p>Participation and completion summary.</p></div></div><?php if(!$rows): ?><div class="sv-empty"><i class="fas fa-chart-column"></i><strong>No report data</strong><span>No cohorts match the selected filters.</span></div><?php else: ?><div class="sv-table-wrap"><table class="sv-table"><thead><tr><th>Programme / Cohort</th><th>Status</th><th>Current</th><th>Active</th><th>Completed</th><th>Withdrawn</th><th>Progress</th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td><div class="sv-person"><div class="sv-avatar"><i class="fas fa-chart-line"></i></div><div class="sv-person__copy"><strong><?= e($row['cohort_name']) ?></strong><span><?= e($row['programme_name']) ?></span></div></div></td><td><span class="sv-status sv-status--<?= e(sv_status_class($row['cohort_status'])) ?>"><?= e(sv_status_label($row['cohort_status'])) ?></span></td><td><?= (int)$row['total_candidates'] ?></td><td><?= (int)$row['active_candidates'] ?></td><td><?= (int)$row['completed_candidates'] ?></td><td><?= (int)$row['withdrawn_candidates'] ?></td><td style="min-width:150px"><div class="sv-progress"><div class="sv-progress__meta"><span>Completion</span><strong><?= (int)$row['rate'] ?>%</strong></div><div class="sv-progress__track"><div class="sv-progress__bar" style="width:<?= (int)$row['rate'] ?>%"></div></div></div></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
<div class="sv-security"><i class="fas fa-shield-halved"></i><div><strong>Scoped reporting</strong><p>Report calculations are based only on cohorts assigned to your Supervisor account.</p></div></div>
<?php require __DIR__ . '/_layout_end.php'; ?>
