<?php
require_once __DIR__ . '/../includes/bootstrap.php';require_role('supervisor');require_once __DIR__ . '/_helpers.php';
$user=current_user();$flashes=render_flashes();$currentPage='update_candidate_status';$pageTitle='Update Candidate';$supervisorId=(int)($user['id']??$user['user_id']??0);$candidateId=(int)($_REQUEST['id']??0);$cohortId=(int)($_REQUEST['cohort_id']??0);if($supervisorId<=0||$candidateId<=0||$cohortId<=0){http_response_code(400);exit('Invalid request.');}
$stmt=Database::prepare("SELECT u.id candidate_id,u.first_name,u.last_name,u.email,cp.id participation_id,cp.status participant_status,c.id cohort_id,c.name cohort_name,p.name programme_name FROM cohort_participants cp JOIN cohorts c ON c.id=cp.cohort_id JOIN programmes p ON p.id=c.programme_id JOIN users u ON u.id=cp.user_id WHERE u.id=? AND c.id=? AND c.supervisor_id=? LIMIT 1",'iii',[$candidateId,$cohortId,$supervisorId]);$candidate=$stmt->get_result()->fetch_assoc();$stmt->close();if(!$candidate){http_response_code(404);exit('Candidate not found in your assigned cohort.');}
$error='';$allowed=['active','completed','withdrawn'];
if($_SERVER['REQUEST_METHOD']==='POST'){$token=(string)($_POST['csrf_token']??'');if(!sv_verify_csrf($token)){$error='Your session token is invalid. Refresh the page and try again.';}else{$newStatus=(string)($_POST['status']??'');if(!in_array($newStatus,$allowed,true)){$error='Invalid candidate status.';}else{$stmt=Database::prepare("UPDATE cohort_participants cp JOIN cohorts c ON c.id=cp.cohort_id SET cp.status=?,cp.completed_at=CASE WHEN ?='completed' THEN COALESCE(cp.completed_at,NOW()) ELSE cp.completed_at END WHERE cp.user_id=? AND cp.cohort_id=? AND c.supervisor_id=?",'ssiii',[$newStatus,$newStatus,$candidateId,$cohortId,$supervisorId]);$stmt->close();header('Location: '.url('supervisor/candidate_view.php?id='.$candidateId.'&cohort_id='.$cohortId));exit;}}}
$fn=trim((string)$candidate['first_name']);$ln=trim((string)$candidate['last_name']);$name=trim($fn.' '.$ln)?:'Candidate';
require __DIR__ . '/_layout_start.php';
?>
<div class="sv-page-header"><div><span class="sv-eyebrow">Participation Status</span><h2>Update <?= e($name) ?></h2><p>Update participation status within <?= e($candidate['cohort_name']) ?>. This does not move the candidate or alter cohort assignment.</p></div><div class="sv-actions"><a class="sv-btn sv-btn--secondary" href="<?= url('supervisor/candidate_view.php?id='.$candidateId.'&cohort_id='.$cohortId) ?>"><i class="fas fa-arrow-left"></i> Cancel</a></div></div>
<?php if($error!==''): ?><div class="sv-security" style="background:var(--sv-red-soft);border-color:rgba(220,38,38,.18)"><i class="fas fa-triangle-exclamation" style="color:var(--sv-red)"></i><div><strong><?= e($error) ?></strong></div></div><?php endif; ?>
<section class="sv-card" style="max-width:720px"><div class="sv-card__header"><div><h3>Status Update</h3><p>Allowed Supervisor statuses are Active, Completed and Withdrawn.</p></div></div><div class="sv-card__body"><form method="post"><input type="hidden" name="id" value="<?= $candidateId ?>"><input type="hidden" name="cohort_id" value="<?= $cohortId ?>"><input type="hidden" name="csrf_token" value="<?= e(sv_csrf_token()) ?>"><div class="sv-field" style="margin-bottom:16px"><label>Candidate</label><input class="sv-input" value="<?= e($name.' · '.$candidate['programme_name'].' · '.$candidate['cohort_name']) ?>" disabled></div><div class="sv-field" style="margin-bottom:18px"><label>Participation Status</label><select class="sv-select" name="status" required><?php foreach($allowed as $s): ?><option value="<?= e($s) ?>" <?= $candidate['participant_status']===$s?'selected':'' ?>><?= e(sv_status_label($s)) ?></option><?php endforeach; ?></select></div><div class="sv-actions"><button class="sv-btn sv-btn--primary" type="submit"><i class="fas fa-floppy-disk"></i> Save Status</button><a class="sv-btn sv-btn--secondary" href="<?= url('supervisor/candidate_view.php?id='.$candidateId.'&cohort_id='.$cohortId) ?>">Cancel</a></div></form></div></section>
<div class="sv-security"><i class="fas fa-shield-halved"></i><div><strong>Supervisor permissions</strong><p>This workflow only updates participation status. Candidate assignment, cohort reassignment and Supervisor assignment remain outside this page.</p></div></div>
<?php require __DIR__ . '/_layout_end.php'; ?>
